### ISSUE TITLE
Creation de reunion

### ISSUE THREAD

**Issue by acouderc** [WeAreMuffin/Muffin#13]
Lorsque j'ai voulu creer une reunion(pour le jour meme, a 8h), l'heure enregistree fut minuit et non 8h00 comme voulu.

En duree de reunion, j'ai rentre .50 (ou 0,50) au lieu de l'heure entiere proposee.

**Comment by lambda2** [comment]
Ouaip, c'est noté, merci !
Pour la durée de réunion par contre, c'est volontaire, vu que je me suis dit que personne sait combien de temps va durer une réunion _à la minute près_, mais ca peut être discutable...
Tu penses que le delta de 1h est trop grand ?

**Comment by acouderc** [comment]
Ca depend de ton optique. Si tu pars sur des grosses reunions formelles
j'imagine qu'une heure est bien, mais il doit etre possible d'organiser de
petites reunions de 10 minutes dans la journee egalement. Dans les deux cas
je ne pense pas que c'est un probleme, j'ai juste mis .5 pour voir comment
reagissait le formulaire si on lui donnait une valeur non prevue.

**Comment by lambda2** [comment]
Ca marche :) Bon je vais rester sur une base horaire alors, tout marchera bien mieux dans la prochaine version, qui passe en prod dans quelques jours.
