### ISSUE TITLE
Mettre en place un calendrier

### ISSUE THREAD

**Issue by acouderc** [WeAreMuffin/Muffin#18]
Salut !

J'avais comme projet de creer un calendrier des evenements pour l'ecole (http://teamup.com/ks10d843cc6494361e/), afin que chacun puisse s'y retrouver dans les activites proposees par les eleves et l'ecole.

Maintenant que Muffin integre les reunions, il serait probablement plus pertinent d'integrer le calendrier a Muffin plutot qu'avoir quelque chose de separe.

Il y a apparemment pas mal de plugins jquery qui permettent d'en creer, une autre solution serait d'integrer un Google Calendar pour ceux qui l'utilisent et voudraient l'integrer dans leur calendrier perso, on me l'avait demande ici : https://intra.42.fr/forum/#!/General/Planning-des-activites-de-la-semaine.

Puisque je propose l'idee, il me parait normal d'aider a la realisation, si mon aide vous interesse il me faudrait probablement une explication de la structure du code.

**Comment by lambda2** [comment]
**Salut Antoine !**

Effectivement, ça pourrait être une super idée de faire un calendrier !
Ça serait aussi génial que tu aides à la réalisation, surtout si tu veux que ça voies le jour _assez vite_, parce que j'ai pas beaucoup de temps à consacrer à Muffin, et j'ai déjà une TODO list un peu pénible à faire... :smiley:, notamment en ce qui concerne le fix de plein de petits bugs que me rapportent les gens par mail... (ça m'enchantes que tu ouvres des issues d'ailleurs).

Si tu veux que je te brief un peu sur le fonctionnement interne de Muffin, il va falloir que tu me guides... En gros, le site est en php, repose sur [un framework maison](https://github.com/lambda2/Moon), et suit un pattern [MVC](http://fr.wikipedia.org/wiki/Mod%C3%A8le-vue-contr%C3%B4leur).

En fait, je pars déjà peut être un peu loin... j'essaie de te mp, sinon je passerai te voir !

**Comment by lambda2** [comment]
Calendrier basique ajouté en 4.20 (5b3424f255bad0d2dfc66e3e3f5e1ae2884cdc9b)
