### ISSUE TITLE
Inscription impossible

### ISSUE THREAD

**Issue by acouderc** [WeAreMuffin/Muffin#34]
fpons m'a dit qu'il est impossible de s'inscrire depuis que les identifiants 42 sont proposes.

Il ne considere pas fiable l'utilisation de ses identifiants et prefererait recevoir une passphrase.

**Comment by lambda2** [comment]
Ouaip, il se passe un truc bizarre avec ~5% des comptes lors de la connexion ldap... Il faudrait que je leur demande, sans trop d'indiscrétion, si ils ont des caractères spéciaux dans leur pass, je pense que c'est une piste.

Sinon clairement il faut **remettre l'envoi d'un Muffinpass lors de la première connexion** :)

**Comment by lambda2** [comment]
**Note**: Problème du bouton de connexion référencé en #36
