### ISSUE TITLE
Rectification des drafts

### ISSUE THREAD

**Issue by OddNaughty** [WeAreMuffin/Muffin#35]
Hello all,

Déjà gros GG pour le taf fait.
Et petuite idée, ce serait cool de mettre en place une sorte de pull request pour la modification d'un draft, à l'image d'un wiki :).
Exemple:

```
buff = malloc(sizeof(char) * 2);
buff[2] = 0;
```

de http://muffin.lambdaweb.fr/#/Drafts/read/2 .
Comme ca, hop on corrige, ou hop on rajoute des trucs "importants", mettons des suggestions et/ou de l'explication de code dans ce cas là et l'auteur recoit un mail demandant une confirmation et paf ca fait des chocapics, le cas échéant un meilleur draft :).

**Comment by lambda2** [comment]
#### Ouaip, c'est prévu, mais c'est assez loin dans la liste des choses à faire :)
- Dans un premier temps, on va déjà donner la possibilité à la personne qui crée le draft de donner des droits en écriture à d'autres personnes. Ça permettra un semblant de collaboratif.
- Ensuite, on mettra un système de _pseudo-pull-requests_ qui permettra de proposer des modifications, ce qui serait génial je te l'accorde :smiley:  (ne serait-ce que pour corriger les fautes d'orthographe).

**Comment by OddNaughty** [comment]
Cool cool, bah bonne chance alors :).

**Comment by lambda2** [comment]
Hey, ferme pas l'issue :smile: 
On la fermera quand ca sera réglé !

**Comment by OddNaughty** [comment]
Pardon pardon, vous aviez répondu a la question :X.
