### ISSUE TITLE
Muffin - Parce que les drafts, ca va bientot déborder

### ISSUE THREAD

**Issue by ghost** [WeAreMuffin/Muffin#39]
Bonjour,

Comment commander des muffins sur votre site ? Je ne comprends pas.

Cordialement.

**Comment by ghost** [comment]
(sinon, pour les drafts, quand y'en aura beaucoup faudra trouver un moyen de classer (hashtag, catégories?)

**Comment by lambda2** [comment]
La commande de muffins est en préparation, on attend le four !
Pour les drafts, on va refaire complètement la mise en page, enlever le système de tri dynamique (beaucoup de kikoostyle pour beaucoup trop de ressources... ça tue mon navigateur quand je teste  un tri avec 30 ~ 40 éléments) et mettre des tags + une petite barre de recherche

**Comment by ghost** [comment]
trop de swag
