### ISSUE TITLE
Draft avec titre mais sans contenu non enregistré

### ISSUE THREAD

**Issue by pandark** [WeAreMuffin/Muffin#40]
Lorsqu'on enregistre un draft avec un titre mais sans contenu, rien ne se passe, ni erreur ni enregistrement.

Reproduction du bug :
1. Aller sur la page Drafts
2. Cliquer sur Nouveau
3. Modifier le titre
4. Cliquer sur Enregistrer : la petite image verte s'affiche, pas de signalement d'erreur.
5. Retourner sur la page des drafts : Il n'y a pas de nouveau draft.

**Comment by lambda2** [comment]
Ah ! C'est noté ! Merci ! :)
