### ISSUE TITLE
Ne peux se connecter avec son login 42 et son mdp

### ISSUE THREAD

**Issue by RoseChantelune** [WeAreMuffin/Muffin#42]
Moi ainsi qu'un ami a 42 n'arrivont pas a nous connecter a muffin. Est-ce parce que nous sommes des petits nouveaux de cette annee ?
Merci d'avance de regler ce bug :D !

**Comment by lambda2** [comment]
Ca doit être bon maintenant, les infos ne sont peut être pas bonnes, je ferais une import propre des que j'ai le temps :smile:
