### ISSUE TITLE
Aide proposee "automatiquement" sans clic.

### ISSUE THREAD

**Issue by osoliver** [WeAreMuffin/Muffin#5]
Afin de tester le site, je me suis inscrit comme "helper" pour le projet ft select. J'ai propose mon aide a plusieurs personnes. un pote a signalé vouloir recevoir de l'aide. Il a ainsi recu 5 demandes (a chaque tentative d'affichage de la page de ma part car le site bugguait) alors qu'aucun bouton n'a ete cliqué suite a son inscription.

**Comment by lambda2** [comment]
**Merci d'avoir signalé !**

Le problème devrait être résolu avec le passage en [version 2.20](https://github.com/lambda2/Muffin/releases/tag/2.20) 33b85f90f00b00aaed00095979e0213b1604a39e _(C'est a dire dans quelques minutes !)_

N’hésites pas a refaire un ticket si le problème n'est toujours pas résolu !
