### ISSUE TITLE
Chargement impossible

### ISSUE THREAD

**Issue by KbuenoTTV** [WeAreMuffin/Muffin#7]
Apres avoir rajouté une petite etoile dans plusieurs champs et proposé/demandé de l'aide dans d'autres, je reactualise ma page et attends la barre de chargement ...

La barre de chargement se bloque a la derniere barre. Chargement donc impossible pour moi.

Merci pour le site :)

**Comment by lambda2** [comment]
Vu ! on va voir si ce genre de probleme revient, je n'arrive pas a reproduire le bug.
