### ISSUE TITLE
Crash a la connection.

### ISSUE THREAD

**Issue by darnuria** [WeAreMuffin/Muffin#9]
J'ai tenter de me connecter avec une pass-phrase envoyer depuis 2semaines. résultat :
Ps : je t'ai aussi envoyer un mail avec un pdf de la page.

Allumez la cafetière...

```
Access Denied

Dans le fichier /var/www/html/Muffin/Moon/Classes/Router/Router.php @ 265
Router -> routeGet()

Dans le fichier /var/www/html/Muffin/Moon/Classes/Router/Router.php @ 604
Router -> route()

Dans le fichier /var/www/html/Muffin/Moon/Classes/Core/Core.php @ 256
Core :: route()

Dans le fichier /var/www/html/Muffin/index.php @ 15
```

Contenu des formulaires
Post
Key     Value   Lenght  Type
Get
Key     Value   Lenght  Type
p   'User->index'   

11

string

Analyse de l'application
Etat du Core
Démarré
Chargement des fichiers de configuration
Les fichiers sont correctement chargés
Amorçage du Core
User Config File    Passé
Default Config File Passé
Generate Config Vars    Passé
Database Connexion  Passé
Engine Start    Passé
Table Scheme Generation Passé

Comment le reproduire.

j'ai envoyer la chaine de caractère entre crochets exemple :
[ Je suis une méchante chaine. ]
j'envoie
Je suis une méchante chaine.

**Comment by lambda2** [comment]
Salut !

Merci d'avoir signalé !
On va essayer de régler ça ASAP, ça vient du fait que l'ancienne session est toujours présente mais obsolète... Il faut clear tous les cookies pour que ça marche. Voici un démarache possible pour Google Chrome :

> - Clic droit
> - Inspecter l'element
> - Ressources
> - Cookies
> - 88.183.177.155
> - Effacer tous les cookies
>   Ensuite, redemander un nouveau mot de passe.

Demain soir (mercredi 15/01/2014), on devrait faire un grosse maj (d'ailleurs le site sera offline ~ 5h) qui fixera ce genre de bugs.

**Comment by darnuria** [comment]
Hum je suis sous firefox-nightly.
j'ai clean tout mes cookies du coup.
